# Generated by Django 4.1 on 2022-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('cs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('start', models.DateField(auto_now=True)),
                ('end', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ARCHIVED', 'Archived'), ('BOOKED', 'Booked')], default='Created', max_length=10)),
            ],
        ),
    ]
