# Generated by Django 4.1 on 2022-08-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_campaign_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Archived', 'Archived'), ('Booked', 'Booked')], default='Created', max_length=10),
        ),
    ]
