# Generated by Django 4.1 on 2022-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
